### ISSUE TITLE
Ability to stop listening in JS SDK

### ISSUE THREAD

**Issue by KATT** [tryretool/retoolrpc#23]
## What

`.listen()` currently loops forever AFAICT and I can't find any way of stopping it which likely[^1] leads to non-graceful shutdowns.

## How

It'd be nice if the SDK would be

```ts
const rpc = new RetoolRPC({
  // [...]
});

console.log('Connecting to Retool....');
const stop = await rpc.listen();

console.log('Listening on Retool');

await stop();
console.log('Retool stopped listening');
```

[^1]: I'm still evaluating if we should be using Retool RPC or continue how we're doing stuff now so I'm not sure it leads to a non-graceful shutdown

**Comment by huytool157** [comment]
Noted! Will work on it whenever we have time.

**Comment by huytool157** [comment]
Noted, will work on adding a `stop` mechanism soon.

**Comment by KATT** [comment]
As I mentioned [here](https://github.com/tryretool/retoolrpc/issues/9#issuecomment-2004087551), it'd be even nicer if it was webhook/push based so we wouldn't have to care about state at all
