### ISSUE TITLE
Return implementation when registering function to make tests easier

### ISSUE THREAD

**Issue by KATT** [tryretool/retoolrpc#24]
See #22 for more details

**Comment by huytool157** [comment]
Thanks for contributing, @KATT! I'm a big fan of your work on tRPC. I use it extensively in my side projects, and I've been thinking of a similar solution for our Retool monorepo.

Out of curiosity, are you using Retool RPC in production? What does your tech stack look like, and what's your use case? I'd be more than happy to chat!
